// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Operacao.Context;

#nullable disable

namespace Manutencao.Migrations
{
    [DbContext(typeof(OperacaoContext))]
    [Migration("20241204141026_Reparo")]
    partial class Reparo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Manutencao.Entities.Reparo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Local")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maq")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Problema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reparos");
                });
#pragma warning restore 612, 618
        }
    }
}
